site_name: MkLorum
docs_dir: docs
theme:
  name: material
  # name: readthedocs
  palette:
    primary: blue
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js
  - javascript/hljs.js
extra_css:
  - https://raw.githubusercontent.com/highlightjs/highlight.js/master/src/styles/github.css
  - css/abap-docs.css
markdown_extensions:
  - admonition  
  - pymdownx.extra
  - pymdownx.superfences